---
include:
- "**/*.rb"
exclude:
- spec/**/*
- lib/solargraph/rails/annotations/**/*
- vendor/**/*
- ".bundle/**/*"
require:
  - solargraph
  - active_support
  - active_support/core_ext/string/inflections
domains: []
reporters: []
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
