source 'https://rubygems.org'

gem 'rails', '~> 7.1.0'
gem 'devise'
gem 'sqlite3'

gem 'solargraph-rails', path: '../..'

gem 'solargraph',
    github: 'apiology/solargraph',
    branch: '2025-04-28'
