# To debug locally:
#   npm install -g act
#   act act pull_request
#

name: Ruby

on:
  workflow_dispatch: {}
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - "3.0"
#          - "3.1"
#          - "3.2"
#          - "3.3"
#          - "3.4"
        solargraph-version:
          - "0.48.0"
          - "0.49.0"
          - "0.50.0"
          - "0.51.2"
          - "0.52.0"
          - "0.54.6.alpha"
          - "0.55.alpha"
        rails-version:
          - "7"
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: cache gemfile.lock for better cache stability
        uses: actions/cache@v3
        id: gemfilelock
        with:
          key: ${{ runner.os }}-gemfilelock-${{ matrix.ruby-version }}
          path: |
            ${{ env.GITHUB_WORKSPACE }}/Gemfile.lock

      - uses: ruby/setup-ruby@v1
        env:
          MATRIX_SOLARGRAPH_VERSION: ${{ matrix.solargraph-version }}
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: latest
          bundler-cache: true
          cache-version: ${{ matrix.solargraph-version }}-2025-04-29

      - name: Install child bundle
        run: |
          set -x
          export MATRIX_SOLARGRAPH_VERSION="${{ matrix.solargraph-version }}"
          export BUNDLE_PATH=$(pwd)/vendor/bundle
          # next linel from README.md
          bundle exec rbs --version
          cd spec/rails${{ matrix.rails-version }}
          bundle install
          rbs --version
          ( rbs collection init; rbs collection install)
          rbs collection update
          cd ../..

      - name: Restore cache of gem annotations
        id: dot-cache-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-dot-cache-${{ matrix.ruby-version }}-${{ matrix.solargraph-version }}-4
          path: |
            /home/runner/.cache/solargraph

      - name: bundle list
        run: bundle list && cat Gemfile.lock && find vendor -name Gemfile
        env:
          MATRIX_SOLARGRAPH_VERSION: ${{ matrix.solargraph-version }}

      #- name: Setup upterm session
      #  uses: lhotari/action-upterm@v1

      - name: RSpec
        run: |
          set -x
          echo $MATRIX_SOLARGRAPH_VERSION
          export MATRIX_SOLARGRAPH_VERSION="${{ matrix.solargraph-version }}"
          export BUNDLE_PATH=$(pwd)/vendor/bundle
          ruby --version
          bundle install
          bundle update solargraph
          bundle exec solargraph version
          bundle info solargraph
          bundle exec solargraph gems || true
          bundle exec rspec spec/solargraph-rails

      - name: Cache gem annotations
        id: dot-cache-save
        if: always() && steps.dot-cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ runner.os }}-dot-cache-${{ matrix.ruby-version }}-${{ matrix.solargraph-version }}-4
          path: |
            /home/runner/.cache/solargraph
