# To debug locally:
#   npm install -g act
#   act act pull_request
#

name: Ruby

on:
  workflow_dispatch: {}
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.0"
#          - "3.1"
#          - "3.2"
#          - "3.3"
#          - "3.4"
        solargraph-version:
          - "0.48.0"
          - "0.49.0"
#          - "0.50.0"
#          - "0.51.2"
#          - "0.52.0"
        rails-version:
          - "7"
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          bundler: latest
          cache-version: 2
      - name: cache gem annotations
        uses: actions/cache@v3
        id: dot-cache
        with:
          key: ${{ runner.os }}-dot-cache-${{ matrix.ruby-version }}
          path: |
            /home/runner/.cache
      #- name: Setup upterm session
      #  uses: lhotari/action-upterm@v1
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: spec/rails${{ matrix.rails-version }}
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: bundle list
        run: bundle list && cd spec/rails7 && bundle list && cat Gemfile.lock

      - name: RSpec
        run: bundle exec rspec spec/solargraph-rails
